language: cpp
os:
- linux
compiler:
- gcc
# deactivate clang until the tests run smoothly under gcc
#- clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo apt-get update -qq
install:
  - sudo apt-get install libboost-serialization-dev libboost-test-dev libhdf5-serial-dev
  - sudo apt-get install cmake
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "g++" ]; then g++ --version; fi
  - if [ "$CXX" = "clang++" ]; then clang++ --version; fi
  - cmake --version

script:
  - mkdir build && cd build
  - cmake -DECHELON_BUILD_TESTS=ON ../
  - make
  - make test