language: cpp
os:
- linux
compiler:
- gcc
- clang
env:
- TEST_COVERAGE=false

matrix:
  include:
    - compiler: gcc
      env: TEST_COVERAGE=true

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - wget http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2/download -O boost.tar.bz2
  - tar jxf boost.tar.bz2
  - export BOOST_ROOT="$PWD/boost_1_55_0"
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz -O cmake.tar.gz
  - tar zxf cmake.tar.gz
  - wget http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.12/src/hdf5-1.8.12.tar.bz2 -O hdf5.tar.bz2
  - tar jxf hdf5.tar.bz2
install:
  - if [ "$TEST_COVERAGE" = true ]; then sudo pip install cpp-coveralls; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - $CXX --version
  - if [ "$TEST_COVERAGE" = true ]; then gcov-4.9 --version; fi
  - cmake --version
  - cd $BOOST_ROOT
  - ./bootstrap.sh
  - ./b2 toolset=$CC -q -d0 variant=release link=shared --with-serialization --with-system --with-exception --with-test install --prefix=/tmp/boost
  - cd $TRAVIS_BUILD_DIR
  - cd cmake-2.8.12.2
  - ./bootstrap --prefix=/tmp/cmake
  - make install
  - cd $TRAVIS_BUILD_DIR
  - cd hdf5-1.8.12
  - ./configure --prefix=/tmp/hdf5 --disable-static --enable-hl --enable-threadsafe --enable-linux-lfs --enable-production --with-pic --with-pthread --disable-sharedlib-rpath
  - make install 2> /dev/null
  - export HDF5_ROOT=/tmp/hdf5
  - cd $TRAVIS_BUILD_DIR

script:
  - mkdir build && cd build
  - if [ "$TEST_COVERAGE" = false ]; then /tmp/cmake/bin/cmake -DECHELON_BUILD_TESTS=ON -DBOOST_ROOT=/tmp/boost ../ && make && make test; fi
  - if [ "$TEST_COVERAGE" = true ]; then /tmp/cmake/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE_ENABLE=ON -DECHELON_BUILD_TESTS=ON -DBOOST_ROOT=/tmp/boost ../ && make && make test; fi
  
after_success:
  - if [ "$TEST_COVERAGE" = true ]; then coveralls --gcov gcov-4.9 --gcov-options '\-lp'; fi